title: Using seed in Python
hero_image: images/banner.png
description: How to use seed in Python
version: 4
listed: false
copyedit: false
last_tested: "2021-08-13"
steps:
  - title: Using seed in Python
