---
title: Usar seed (semilla) en Python
hero_image: images/banner.png
description: Cómo usar seed (semilla) en Python
version: 4
listed: false
copyedit: false
last_tested: "2021-08-13"
steps:
  - 
    title: Usar seed (semilla) en Python
