---
title: Usar semillas en Python
hero_image: images/banner.png
description: Cómo usar semillas en Python
version: 4
listed: false
copyedit: false
last_tested: "2021-08-13"
steps:
  - 
    title: Usar semillas en Python
