---
title: Defnyddio dosbarthiad yn Python
hero_image: images/banner.png
description: Sut mae defnyddio dosbarthiad yn Python
version: 4
listed: false
copyedit: false
last_tested: "2021-08-13"
steps:
  - title: Defnyddio dosbarthiad yn Python
