---
title: Usando seed em Python
hero_image: images/banner.png
description: Como usar seed em Python
version: 4
listed: false
copyedit: false
last_tested: "2021-08-13"
steps:
  - 
    title: Usando seed em Python
