---
title: Utilizzo della funzione seed in Python
hero_image: images/banner.png
description: Come usare la funzione seed in Python
version: 4
listed: false
copyedit: false
last_tested: "2021-08-13"
steps:
  - 
    title: Utilizzo della funzione seed in Python
